os: linux
dist: trusty
sudo: required
language: cpp

matrix:
  include:
    # Clang 5, debug
    - env: CC_COMP=clang-5.0 CXX_COMP=clang++-5.0 BUILD_TYPE=debug
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7

    # GCC 7, debug
    - env: CC_COMP=gcc-7 CXX_COMP=g++-7 BUILD_TYPE=debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

    # Clang 5, release
    - env: CC_COMP=clang-5.0 CXX_COMP=clang++-5.0 BUILD_TYPE=release
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - g++-7

    # GCC 7, release
    - env: CC_COMP=gcc-7 CXX_COMP=g++-7 BUILD_TYPE=release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

install:
  # thank god we only need the Boost headers
  - cd "$TRAVIS_BUILD_DIR"
  - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
  - tar -xf boost_1_67_0.tar.bz2

before_script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir build && cd build
  - export CC=$CC_COMP
  - export CXX=$CXX_COMP
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBOOST_INCLUDEDIR="$TRAVIS_BUILD_DIR/boost_1_67_0"

script:
  - make -j2 VERBOSE=1 && make check
