# See: <https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml>

name: CMake on a single platform
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  BUILD_TYPE: Debug
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pytest
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
          boost_version: 1.74.0
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS='-Wall -Wextra -pedantic'
        env:
          BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t tests
      - name: Test
        working-directory: ${{github.workspace}}/tests
        run: |
          export YACTFR_BINARY_DIR=${{github.workspace}}/build
          pytest
